import streamlit as st
import PSYCOPG2

CONN = PSYCOPG2.CONNECT(
    HOST=ST.SECRETS["DB_HOST"],
    DATABASE= ST.SECRETS["DB_NAME"],
    USER=ST.SECRETS["DB_USER"],
    PASSWORD=ST.SECRETS["DB_PASSWORD"],
    PORT=ST.SECRETS["DB_PORT"]
)

CURSOR = CONN.CURSOR()

st.title("sistema de cadastro")
st.write("bem-vindo ao sistema!")

CURSOR.EXECUTE("SELECT NOME,EMAIL FROM CLIENTE")
DADOS = CURSOR.FETCHALL()
for NOME, EMAIL in DADOS:
ST.write(F"{NOME} = {EMAIL}")


NOME = ST.TEXT_INPUT("NOME")
EMAIL = ST.TEXT_INPUT("EMAIL")

if ST.BUTTON("CADASTRAR"):
CURSOR.EXECUTE(
    "INSERT INTO CLIENTE (NOME, CPF, EMAIL) VALUES (%S,%$,%$)",
    (NOME,"000001", EMAIL)
)
CONN.COMMIT()
ST.SUCCEESS("CADASTRADO COM SUCESSO!")